#!/usr/bin/env python3
"""Generate README.md and docs/* from data/.

Nothing under docs/ or README.md should ever be hand-edited — edit the YAML in
data/ and re-run this script.

    python scripts/build.py
"""

from __future__ import annotations

import datetime as dt
import re
import urllib.parse

from common import (
    ROOT,
    load_benchmarks,
    load_papers,
    load_taxonomy,
    section_index,
    sort_key,
)

GENERATED = "<!-- BEGIN GENERATED -->"
GENERATED_END = "<!-- END GENERATED -->"
BANNER = (
    "<!-- This file is generated by scripts/build.py. Edit data/*.yaml instead. -->"
)


def anchor(text: str) -> str:
    slug = text.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    return re.sub(r"[\s_]+", "-", slug).strip("-")


def fallback_link(paper: dict) -> str:
    """When we have no resolved URL, point at a search rather than nothing."""
    query = urllib.parse.quote_plus(paper["title"])
    return f"https://www.semanticscholar.org/search?q={query}"


def render_links(paper: dict) -> str:
    links = paper.get("links") or {}
    parts = []
    paper_url = links.get("paper")
    if paper_url:
        parts.append(f"[paper]({paper_url})")
    else:
        parts.append(f"[search]({fallback_link(paper)})")
    for label in ("code", "data", "project"):
        if links.get(label):
            parts.append(f"[{label}]({links[label]})")
    return " · ".join(parts)


def render_paper(paper: dict, show_new: bool = True) -> list[str]:
    star = "⭐ " if "must-read" in (paper.get("tags") or []) else ""
    new = ""
    if show_new and not paper.get("in_survey", True):
        new = " `NEW`"
    venue = paper.get("venue") or "n/a"
    year = paper.get("year", "")
    head = f"- {star}**{paper['title']}**{new}  "
    meta = f"  *{paper.get('authors', 'unknown')}* — {venue} {year} · {render_links(paper)}"
    lines = [head, meta]
    if paper.get("tldr"):
        tldr = " ".join(str(paper["tldr"]).split())
        lines[-1] += "  "
        lines.append(f"  > {tldr}")
    return lines


def build_toc(taxonomy: dict, papers: list[dict]) -> list[str]:
    counts: dict[str, int] = {}
    for paper in papers:
        counts[paper["subsection"]] = counts.get(paper["subsection"], 0) + 1
    out = ["## Contents", ""]
    out.append(f"- [🔥 New since the survey](#-new-since-the-survey)")
    for section in taxonomy["sections"]:
        total = sum(counts.get(sub["key"], 0) for sub in section["subsections"])
        title = f"{section['title']} ({section['survey_section']})"
        out.append(f"- [{title}](#{anchor(title)}) — {total} papers")
        for sub in section["subsections"]:
            n = counts.get(sub["key"], 0)
            if n:
                out.append(f"  - [{sub['title']}](#{anchor(sub['title'])}) — {n}")
    out.append("- [Benchmarks](#benchmarks)")
    out.append("- [Contributing](#contributing)")
    out.append("")
    return out


def build_new_feed(papers: list[dict]) -> list[str]:
    new = [p for p in papers if not p.get("in_survey", True)]
    new.sort(key=lambda p: (p.get("date") or f"{p.get('year', 0)}-00"), reverse=True)
    out = [
        "## 🔥 New since the survey",
        "",
        "Papers that appeared **after** the survey was finalised (January 2026). "
        "This feed is the working set for the next revision — "
        f"currently **{len(new)}** entries.",
        "",
    ]
    if not new:
        out += ["_Nothing yet._", ""]
        return out
    current = None
    for paper in new:
        month = paper.get("date") or str(paper.get("year"))
        if month != current:
            current = month
            out.append(f"**{month}**")
            out.append("")
        out += render_paper(paper, show_new=False)
        out.append("")
    return out


def build_sections(taxonomy: dict, papers: list[dict]) -> list[str]:
    by_sub: dict[str, list[dict]] = {}
    for paper in papers:
        by_sub.setdefault(paper["subsection"], []).append(paper)

    out: list[str] = []
    for section in taxonomy["sections"]:
        out.append(f"## {section['title']} ({section['survey_section']})")
        out.append("")
        if section.get("blurb"):
            out.append(f"> {' '.join(section['blurb'].split())}")
            out.append("")
        for sub in section["subsections"]:
            entries = sorted(by_sub.get(sub["key"], []), key=sort_key)
            if not entries:
                continue
            out.append(f"### {sub['title']}")
            out.append("")
            if sub.get("blurb"):
                out.append(f"_{' '.join(sub['blurb'].split())}_")
                out.append("")
            for paper in entries:
                out += render_paper(paper)
                out.append("")
    return out


def build_benchmarks(benchmarks: list[dict]) -> list[str]:
    out = [
        "## Benchmarks",
        "",
        "Resources built specifically to measure analogical ability "
        f"({len(benchmarks)} total). Full detail in "
        "[docs/benchmarks.md](docs/benchmarks.md).",
        "",
        "| Benchmark | Year | Modality | Task | Scale | Links |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for bench in sorted(benchmarks, key=lambda b: (-b.get("year", 0), b["name"])):
        links = bench.get("links") or {}
        link_cells = " · ".join(f"[{k}]({v})" for k, v in links.items() if v) or "—"
        new = " `NEW`" if bench.get("new_since_survey") else ""
        scale = " ".join(str(bench.get("scale", "")).split())
        out.append(
            f"| **{bench['name']}**{new} | {bench.get('year', '')} "
            f"| {bench.get('modality', '')} | {bench.get('task', '')} "
            f"| {scale} | {link_cells} |"
        )
    out.append("")
    return out


def build_stats(papers: list[dict], benchmarks: list[dict]) -> str:
    new = sum(1 for p in papers if not p.get("in_survey", True))
    return (
        f"**{len(papers)}** papers · **{len(benchmarks)}** benchmarks · "
        f"**{new}** added since the survey · "
        f"last updated {dt.date.today().isoformat()}"
    )


# ---------------------------------------------------------------- doc views --


def view_by_year(papers: list[dict]) -> str:
    out = [BANNER, "", "# Papers by year", ""]
    by_year: dict[int, list[dict]] = {}
    for paper in papers:
        by_year.setdefault(int(paper.get("year", 0)), []).append(paper)
    for year in sorted(by_year, reverse=True):
        out.append(f"## {year} ({len(by_year[year])})")
        out.append("")
        for paper in sorted(by_year[year], key=sort_key):
            out += render_paper(paper)
            out.append("")
    return "\n".join(out)


def view_by_tag(papers: list[dict], taxonomy: dict) -> str:
    out = [BANNER, "", "# Papers by tag", ""]
    vocab = taxonomy.get("tags", {})
    by_tag: dict[str, list[dict]] = {}
    for paper in papers:
        for tag in paper.get("tags") or []:
            by_tag.setdefault(tag, []).append(paper)
    for tag in sorted(by_tag):
        out.append(f"## `{tag}` ({len(by_tag[tag])})")
        out.append("")
        if tag in vocab:
            out.append(f"_{vocab[tag]}_")
            out.append("")
        for paper in sorted(by_tag[tag], key=sort_key):
            out += render_paper(paper)
            out.append("")
    return "\n".join(out)


def view_taxonomy(taxonomy: dict) -> str:
    out = [
        BANNER,
        "",
        "# Taxonomy",
        "",
        "The five pillars below mirror the survey's structure. When you add a "
        "paper, pick the **single** subsection that best describes its primary "
        "contribution and express everything else with `tags`.",
        "",
        '<p align="center">',
        '  <img src="../figures/taxonomy.png" width="85%" '
        'alt="Taxonomy of analogical reasoning in LLMs">',
        "</p>",
        "",
    ]
    for section in taxonomy["sections"]:
        out.append(f"## {section['title']} — survey {section['survey_section']}")
        out.append("")
        if section.get("blurb"):
            out.append(" ".join(section["blurb"].split()))
            out.append("")
        for sub in section["subsections"]:
            out.append(f"### `{sub['key']}` — {sub['title']}")
            out.append("")
            if sub.get("blurb"):
                out.append(" ".join(sub["blurb"].split()))
                out.append("")
    out.append("## Tag vocabulary")
    out.append("")
    for tag, desc in (taxonomy.get("tags") or {}).items():
        out.append(f"- `{tag}` — {desc}")
    out.append("")
    return "\n".join(out)


def view_benchmarks(benchmarks: list[dict]) -> str:
    out = [BANNER, "", "# Benchmarks", ""]
    for bench in sorted(benchmarks, key=lambda b: (-b.get("year", 0), b["name"])):
        new = " `NEW`" if bench.get("new_since_survey") else ""
        out.append(f"## {bench['name']}{new} ({bench.get('year', '')})")
        out.append("")
        out.append(f"- **Task:** {bench.get('task', '')}")
        out.append(f"- **Modality:** {bench.get('modality', '')} / {bench.get('level', '')}")
        out.append(f"- **Scale:** {' '.join(str(bench.get('scale', '')).split())}")
        if bench.get("description"):
            out.append(f"- **Notes:** {' '.join(bench['description'].split())}")
        for label, url in (bench.get("links") or {}).items():
            if url:
                out.append(f"- **{label}:** {url}")
        out.append("")
    return "\n".join(out)


def main() -> None:
    taxonomy = load_taxonomy()
    papers = load_papers()
    benchmarks = load_benchmarks()

    index = section_index(taxonomy)
    unknown = {p["subsection"] for p in papers} - set(index)
    if unknown:
        raise SystemExit(f"unknown subsection(s): {sorted(unknown)} — see data/taxonomy.yaml")

    body: list[str] = []
    body += build_toc(taxonomy, papers)
    body.append("---")
    body.append("")
    body += build_new_feed(papers)
    body.append("---")
    body.append("")
    body += build_sections(taxonomy, papers)
    body.append("---")
    body.append("")
    body += build_benchmarks(benchmarks)

    template = (ROOT / "templates" / "README.head.md").read_text(encoding="utf-8")
    template = template.replace("{{STATS}}", build_stats(papers, benchmarks))
    readme = f"{template.rstrip()}\n\n{GENERATED}\n\n" + "\n".join(body)
    readme += (
        f"\n{GENERATED_END}\n\n"
        + (ROOT / "templates" / "README.foot.md").read_text(encoding="utf-8")
    )
    (ROOT / "README.md").write_text(readme, encoding="utf-8")

    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "by-year.md").write_text(view_by_year(papers) + "\n", encoding="utf-8")
    (docs / "by-tag.md").write_text(view_by_tag(papers, taxonomy) + "\n", encoding="utf-8")
    (docs / "taxonomy.md").write_text(view_taxonomy(taxonomy) + "\n", encoding="utf-8")
    (docs / "benchmarks.md").write_text(view_benchmarks(benchmarks) + "\n", encoding="utf-8")

    print(f"built README.md and 4 docs — {build_stats(papers, benchmarks)}")


if __name__ == "__main__":
    main()
