#!/usr/bin/env python3
"""Generate README.md and docs/* from data/.

Nothing under docs/ or README.md should ever be hand-edited — edit the YAML in
data/ and re-run this script.

    python scripts/build.py
"""

from __future__ import annotations

import re
import urllib.parse

from common import (
    ROOT,
    load_benchmarks,
    load_difficulty,
    load_results,
    load_papers,
    load_taxonomy,
    section_index,
    sort_key,
)

GENERATED = "<!-- BEGIN GENERATED -->"
GENERATED_END = "<!-- END GENERATED -->"
BANNER = (
    "<!-- This file is generated by scripts/build.py. Edit data/*.yaml instead. -->"
)


def anchor(text: str) -> str:
    slug = text.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    return re.sub(r"[\s_]+", "-", slug).strip("-")


def fallback_link(paper: dict) -> str:
    """When we have no resolved URL, point at a search rather than nothing."""
    query = urllib.parse.quote_plus(paper["title"])
    return f"https://www.semanticscholar.org/search?q={query}"


def render_links(paper: dict) -> str:
    links = paper.get("links") or {}
    parts = []
    paper_url = links.get("paper")
    if paper_url:
        parts.append(f"[paper]({paper_url})")
    else:
        parts.append(f"[search]({fallback_link(paper)})")
    for label in ("code", "data", "project"):
        if links.get(label):
            parts.append(f"[{label}]({links[label]})")
    return " · ".join(parts)


def render_paper(paper: dict, show_new: bool = True) -> list[str]:
    star = "⭐ " if "must-read" in (paper.get("tags") or []) else ""
    new = ""
    if paper.get("proposed_addition"):
        priority = paper.get("priority")
        new = f" `PROPOSED · {priority}`" if priority else " `PROPOSED`"
    elif show_new and is_new(paper):
        when = paper.get("date") or paper.get("year")
        new = f" `🔥 {when}`"
    venue = paper.get("venue") or "n/a"
    year = paper.get("year", "")
    head = f"- {star}**{paper['title']}**{new}  "
    meta = f"  *{paper.get('authors', 'unknown')}* — {venue} {year} · {render_links(paper)}"
    lines = [head, meta]
    if paper.get("tldr"):
        tldr = " ".join(str(paper["tldr"]).split())
        lines[-1] += "  "
        lines.append(f"  > {tldr}")
    return lines


def build_toc(taxonomy: dict, papers: list[dict]) -> list[str]:
    counts: dict[str, int] = {}
    for paper in papers:
        counts[paper["subsection"]] = counts.get(paper["subsection"], 0) + 1
    out = ["## Contents", ""]
    out.append("- [🔥 New since the survey](#-new-since-the-survey)")
    if any(p.get("proposed_addition") for p in papers):
        out.append("- [📌 Proposed for the next revision](#-proposed-for-the-next-revision)")
    for section in taxonomy["sections"]:
        total = sum(counts.get(sub["key"], 0) for sub in section["subsections"])
        title = f"{section['title']} ({section['survey_section']})"
        out.append(f"- [{title}](#{anchor(title)}) — {total} papers")
        for sub in section["subsections"]:
            n = counts.get(sub["key"], 0)
            if n:
                out.append(f"  - [{sub['title']}](#{anchor(sub['title'])}) — {n}")
    out.append("- [Benchmarks](#benchmarks)")
    out.append("- [Reported results](#reported-results)")
    out.append("- [Contributing](#contributing)")
    out.append("")
    return out


def is_new(paper: dict) -> bool:
    """Published after the survey — not merely absent from it.

    Proposed additions also carry `in_survey: false`, but most of them predate
    the survey by years (Gick & Holyoak is 1980). Letting them into this feed
    would put 1980 under a "new since January 2026" heading.
    """
    return not paper.get("in_survey", True) and not paper.get("proposed_addition")


def build_new_feed(taxonomy: dict, papers: list[dict]) -> list[str]:
    """A dated index of post-survey work — not a second copy of the entries.

    Every one of these papers is filed in its taxonomy section below, badged
    with its date. Repeating them here in full made the README's first screen a
    duplicate of its second, which buried the taxonomy.
    """
    new = [p for p in papers if is_new(p)]
    new.sort(key=lambda p: (p.get("date") or f"{p.get('year', 0)}-00"), reverse=True)

    sub_title = {}
    for section in taxonomy["sections"]:
        for sub in section["subsections"]:
            sub_title[sub["key"]] = sub["title"]

    out = [
        "## 🔥 New since the survey",
        "",
        f"**{len(new)}** papers published after the survey was finalised "
        "(January 2026). They are filed in the taxonomy below like everything "
        "else and badged with their date — this is just the dated index.",
        "",
    ]
    if not new:
        return out + ["_Nothing yet._", ""]

    out += ["| | Paper | Filed under |", "| --- | --- | --- |"]
    for paper in new:
        links = paper.get("links") or {}
        url = links.get("paper") or fallback_link(paper)
        star = "⭐ " if "must-read" in (paper.get("tags") or []) else ""
        where = sub_title.get(paper["subsection"], paper["subsection"])
        out.append(
            f"| `{paper.get('date') or paper.get('year')}` "
            f"| {star}[{paper['title']}]({url}) "
            f"| [{where}](#{anchor(where)}) |"
        )
    out.append("")
    return out


def build_proposed(taxonomy: dict, papers: list[dict]) -> list[str]:
    """Work the survey should cite but does not — the next revision's worklist."""
    proposed = [p for p in papers if p.get("proposed_addition")]
    if not proposed:
        return []

    titles = {s["key"]: s["title"] for s in taxonomy["sections"]}
    home = {}
    for section in taxonomy["sections"]:
        for sub in section["subsections"]:
            home[sub["key"]] = section["key"]

    out = [
        "## 📌 Proposed for the next revision",
        "",
        f"Papers that belong in the survey but are not cited in v1 — **{len(proposed)}** "
        "of them, from a coverage audit against the taxonomy. Unlike the feed above, "
        "these are not simply newer than the survey; they were missed. "
        "`P1` should be added, `P2` is worth adding, `P3` is optional.",
        "",
    ]
    for priority in ("P1", "P2", "P3"):
        group = [p for p in proposed if p.get("priority") == priority]
        if not group:
            continue
        out.append(f"### {priority} — {len(group)}")
        out.append("")
        out.append("| Paper | Goes in | Why it changes the survey |")
        out.append("| --- | --- | --- |")
        for paper in sorted(group, key=lambda p: p.get("year", 0)):
            links = paper.get("links") or {}
            url = links.get("paper") or fallback_link(paper)
            section = titles.get(home.get(paper["subsection"], ""), "")
            reason = " ".join(str(paper.get("gap_reason", "")).split())
            authors = paper.get("authors", "")
            out.append(
                f"| [{paper['title']}]({url})<br><sub>{authors} · {paper.get('year','')}</sub> "
                f"| {section} | {reason} |"
            )
        out.append("")
    return out


def build_difficulty(difficulty: dict, papers: list[dict], taxonomy: dict) -> list[str]:
    """The §3 difficulty overview, with the failure-mode links made clickable.

    A static table would say the same words; the point of generating it is that
    the "why difficult" column resolves to the failure modes in §3.5 and to
    entries that actually demonstrate the difficulty, so a reader can follow the
    claim to its evidence.
    """
    levels = (difficulty or {}).get("levels") or []
    if not levels:
        return []

    modes = (difficulty or {}).get("failure_modes") or {}
    by_id = {p["id"]: p for p in papers}
    counts: dict[str, int] = {}
    for paper in papers:
        counts[paper["subsection"]] = counts.get(paper["subsection"], 0) + 1
    sub_title = {}
    for section in taxonomy["sections"]:
        for sub in section["subsections"]:
            sub_title[sub["key"]] = sub["title"]

    out = [
        "### Task Difficulty Overview",
        "",
        "How the four categories scale in difficulty, and which structural "
        "property makes each hard. Stars are an editorial judgement about "
        "structural demand, not a measured score — no metric compares across "
        "these categories, which is itself part of the problem.",
        "",
        "| Task type | Description | Difficulty | Why difficult (structural property) | Dominant failure modes | Evidence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for level in sorted(levels, key=lambda x: x.get("difficulty", 0)):
        stars = "★" * level["difficulty"] + "☆" * (5 - level["difficulty"])
        title = sub_title.get(level["subsection"], level["task_type"])
        n = counts.get(level["subsection"], 0)
        fms = " · ".join(
            modes.get(m, {}).get("title", m) for m in (level.get("failure_modes") or [])
        )
        cites = []
        for pid in (level.get("evidence") or [])[:4]:
            paper = by_id.get(pid)
            if not paper:
                continue
            url = (paper.get("links") or {}).get("paper") or fallback_link(paper)
            first = str(paper.get("authors", "")).split(",")[0].split(" and ")[0]
            surname = first.replace(" et al.", "").split()[-1] if first else pid
            cites.append(f"[{surname} {paper.get('year','')}]({url})")
        out.append(
            f"| **[{level['task_type']}](#{anchor(title)})**<br><sub>{n} papers</sub> "
            f"| {' '.join(level['description'].split())} "
            f"| {stars} "
            f"| {' '.join(level['structural_property'].split())} "
            f"| {fms} "
            f"| {', '.join(cites)} |"
        )
    out.append("")
    if modes:
        out.append("<sub>")
        out.append(
            " · ".join(
                f"**{m['title']}** — {' '.join(m['blurb'].split())}" for m in modes.values()
            )
        )
        out.append("</sub>")
        out.append("")
    return out


def build_sections(
    taxonomy: dict, papers: list[dict], difficulty: dict | None = None
) -> list[str]:
    by_sub: dict[str, list[dict]] = {}
    for paper in papers:
        by_sub.setdefault(paper["subsection"], []).append(paper)

    out: list[str] = []
    for section in taxonomy["sections"]:
        out.append(f"## {section['title']} ({section['survey_section']})")
        out.append("")
        if section.get("blurb"):
            out.append(f"> {' '.join(section['blurb'].split())}")
            out.append("")
        if section["key"] == "capability-evaluation":
            out += build_difficulty(difficulty or {}, papers, taxonomy)
        for sub in section["subsections"]:
            entries = sorted(by_sub.get(sub["key"], []), key=sort_key)
            if not entries:
                continue
            out.append(f"### {sub['title']}")
            out.append("")
            if sub.get("blurb"):
                out.append(f"_{' '.join(sub['blurb'].split())}_")
                out.append("")
            for paper in entries:
                out += render_paper(paper)
                out.append("")
    return out


def build_results(results: list[dict], papers: list[dict], difficulty: dict) -> list[str]:
    """Reported numbers, attached to the failure mode each one demonstrates.

    The survey argues qualitatively that models take surface shortcuts. These
    are the measurements that argument rests on, transcribed so a reader can
    check the claim rather than accept it.
    """
    if not results:
        return []
    by_id = {p["id"]: p for p in papers}
    modes = (difficulty or {}).get("failure_modes") or {}

    out = [
        "## Reported results",
        "",
        "Numbers transcribed from the source papers, each tied to the failure "
        "mode it demonstrates. Every figure here is quoted, never estimated; "
        "the `source` field in [`data/results.yaml`](data/results.yaml) says "
        "where in the paper it came from.",
        "",
    ]
    for entry in results:
        paper = by_id.get(entry.get("paper_id"), {})
        links = paper.get("links") or {}
        url = links.get("paper")
        name = f"[{entry['benchmark']}]({url})" if url else entry["benchmark"]
        mode = modes.get(entry.get("demonstrates"), {})
        out.append(f"### {name} — {entry.get('task','')}")
        out.append("")
        if entry.get("setting"):
            out.append(f"_{' '.join(entry['setting'].split())}_")
            out.append("")
        if mode:
            out.append(
                f"**Demonstrates:** {mode.get('title')} — "
                f"{' '.join(mode.get('blurb','').split())}"
            )
            out.append("")
        out.append(f"| Model | Condition | {entry.get('metric','score').title()} | |")
        out.append("| --- | --- | --: | --- |")
        for row in entry.get("rows") or []:
            note = row.get("note", "")
            out.append(
                f"| {row.get('model','')} | {row.get('condition','')} "
                f"| {row.get('score','')} | {note} |"
            )
        out.append("")
        if links.get("code"):
            out.append(f"Official code: {links['code']}")
            out.append("")
    return out


def build_benchmarks(benchmarks: list[dict]) -> list[str]:
    out = [
        "## Benchmarks",
        "",
        "Resources built specifically to measure analogical ability "
        f"({len(benchmarks)} total). Full detail in "
        "[docs/benchmarks.md](docs/benchmarks.md).",
        "",
        "| Benchmark | Year | Modality | Task | Scale | Links |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for bench in sorted(benchmarks, key=lambda b: (-b.get("year", 0), b["name"])):
        links = bench.get("links") or {}
        link_cells = " · ".join(f"[{k}]({v})" for k, v in links.items() if v) or "—"
        new = " `NEW`" if bench.get("new_since_survey") else ""
        scale = " ".join(str(bench.get("scale", "")).split())
        out.append(
            f"| **{bench['name']}**{new} | {bench.get('year', '')} "
            f"| {bench.get('modality', '')} | {bench.get('task', '')} "
            f"| {scale} | {link_cells} |"
        )
    out.append("")
    return out


def build_stats(papers: list[dict], benchmarks: list[dict]) -> str:
    """Counts only — deliberately no build date.

    CI rebuilds and fails the job if the result differs from what is committed,
    so anything time-dependent here would break the build one day later. The
    "Last Commit" shields badge in the header covers freshness instead.
    """
    new = sum(1 for p in papers if is_new(p))
    proposed = sum(1 for p in papers if p.get("proposed_addition"))
    parts = [
        f"**{len(papers)}** papers",
        f"**{len(benchmarks)}** benchmarks",
        f"**{new}** added since the survey",
    ]
    if proposed:
        parts.append(f"**{proposed}** proposed for the next revision")
    return " · ".join(parts)


# ---------------------------------------------------------------- doc views --


def view_by_year(papers: list[dict]) -> str:
    out = [BANNER, "", "# Papers by year", ""]
    by_year: dict[int, list[dict]] = {}
    for paper in papers:
        by_year.setdefault(int(paper.get("year", 0)), []).append(paper)
    for year in sorted(by_year, reverse=True):
        out.append(f"## {year} ({len(by_year[year])})")
        out.append("")
        for paper in sorted(by_year[year], key=sort_key):
            out += render_paper(paper)
            out.append("")
    return "\n".join(out)


def view_by_tag(papers: list[dict], taxonomy: dict) -> str:
    out = [BANNER, "", "# Papers by tag", ""]
    vocab = taxonomy.get("tags", {})
    by_tag: dict[str, list[dict]] = {}
    for paper in papers:
        for tag in paper.get("tags") or []:
            by_tag.setdefault(tag, []).append(paper)
    for tag in sorted(by_tag):
        out.append(f"## `{tag}` ({len(by_tag[tag])})")
        out.append("")
        if tag in vocab:
            out.append(f"_{vocab[tag]}_")
            out.append("")
        for paper in sorted(by_tag[tag], key=sort_key):
            out += render_paper(paper)
            out.append("")
    return "\n".join(out)


def view_taxonomy(taxonomy: dict) -> str:
    out = [
        BANNER,
        "",
        "# Taxonomy",
        "",
        "The five pillars below mirror the survey's structure. When you add a "
        "paper, pick the **single** subsection that best describes its primary "
        "contribution and express everything else with `tags`.",
        "",
        '<p align="center">',
        '  <img src="../figures/taxonomy.png" width="85%" '
        'alt="Taxonomy of analogical reasoning in LLMs">',
        "</p>",
        "",
    ]
    for section in taxonomy["sections"]:
        out.append(f"## {section['title']} — survey {section['survey_section']}")
        out.append("")
        if section.get("blurb"):
            out.append(" ".join(section["blurb"].split()))
            out.append("")
        for sub in section["subsections"]:
            out.append(f"### `{sub['key']}` — {sub['title']}")
            out.append("")
            if sub.get("blurb"):
                out.append(" ".join(sub["blurb"].split()))
                out.append("")
    out.append("## Tag vocabulary")
    out.append("")
    for tag, desc in (taxonomy.get("tags") or {}).items():
        out.append(f"- `{tag}` — {desc}")
    out.append("")
    return "\n".join(out)


def view_benchmarks(benchmarks: list[dict]) -> str:
    out = [BANNER, "", "# Benchmarks", ""]
    for bench in sorted(benchmarks, key=lambda b: (-b.get("year", 0), b["name"])):
        new = " `NEW`" if bench.get("new_since_survey") else ""
        out.append(f"## {bench['name']}{new} ({bench.get('year', '')})")
        out.append("")
        out.append(f"- **Task:** {bench.get('task', '')}")
        out.append(f"- **Modality:** {bench.get('modality', '')} / {bench.get('level', '')}")
        out.append(f"- **Scale:** {' '.join(str(bench.get('scale', '')).split())}")
        if bench.get("description"):
            out.append(f"- **Notes:** {' '.join(bench['description'].split())}")
        for label, url in (bench.get("links") or {}).items():
            if url:
                out.append(f"- **{label}:** {url}")
        out.append("")
    return "\n".join(out)


def main() -> None:
    taxonomy = load_taxonomy()
    papers = load_papers()
    benchmarks = load_benchmarks()
    difficulty = load_difficulty()
    results = load_results()

    index = section_index(taxonomy)
    unknown = {p["subsection"] for p in papers} - set(index)
    if unknown:
        raise SystemExit(f"unknown subsection(s): {sorted(unknown)} — see data/taxonomy.yaml")

    body: list[str] = []
    body += build_toc(taxonomy, papers)
    body.append("---")
    body.append("")
    body += build_new_feed(taxonomy, papers)
    body.append("---")
    body.append("")
    body += build_proposed(taxonomy, papers)
    body.append("---")
    body.append("")
    body += build_sections(taxonomy, papers, difficulty)
    body.append("---")
    body.append("")
    body += build_benchmarks(benchmarks)
    body.append("---")
    body.append("")
    body += build_results(results, papers, difficulty)

    template = (ROOT / "templates" / "README.head.md").read_text(encoding="utf-8")
    template = template.replace("{{STATS}}", build_stats(papers, benchmarks))
    readme = f"{template.rstrip()}\n\n{GENERATED}\n\n" + "\n".join(body)
    readme += (
        f"\n{GENERATED_END}\n\n"
        + (ROOT / "templates" / "README.foot.md").read_text(encoding="utf-8")
    )
    (ROOT / "README.md").write_text(readme, encoding="utf-8")

    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "by-year.md").write_text(view_by_year(papers) + "\n", encoding="utf-8")
    (docs / "by-tag.md").write_text(view_by_tag(papers, taxonomy) + "\n", encoding="utf-8")
    (docs / "taxonomy.md").write_text(view_taxonomy(taxonomy) + "\n", encoding="utf-8")
    (docs / "benchmarks.md").write_text(view_benchmarks(benchmarks) + "\n", encoding="utf-8")

    print(f"built README.md and 4 docs — {build_stats(papers, benchmarks)}")


if __name__ == "__main__":
    main()
